
PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [node1]
ok: [local]
ok: [node2]

TASK [../roles/api : include_tasks] ********************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/api/tasks/config.yml for local, node1, node2

TASK [../roles/api : Create vth group info.] ***********************************
ok: [local]
ok: [node1]
ok: [node2]

TASK [../roles/api : Create user.] *********************************************
ok: [local]
ok: [node2]
ok: [node1]

TASK [../roles/api : Check docker install.] ************************************
ok: [local]
ok: [node2]
ok: [node1]

TASK [../roles/api : include_tasks] ********************************************

TASK [../roles/api : include_tasks] ********************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/api/tasks/service.yml for node1, local, node2

TASK [../roles/api : Restart a container] **************************************
fatal: [local]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))"}
fatal: [node1]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.134.131 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683742897.7667263-159867-43982529354805/AnsiballZ_docker_container.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683742897.7667263-159867-43982529354805/AnsiballZ_docker_container.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683742897.7667263-159867-43982529354805/AnsiballZ_docker_container.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.docker.plugins.modules.docker_container', init_globals=dict(_module_fqn='ansible_collections.community.docker.plugins.modules.docker_container', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_q7lhwhuw/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1288, in <module>\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_q7lhwhuw/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1284, in main\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_q7lhwhuw/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 843, in run_module\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_q7lhwhuw/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/docker_api.py\", line 369, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_q7lhwhuw/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 840, in execute\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_q7lhwhuw/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 211, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_q7lhwhuw/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 272, in present\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_q7lhwhuw/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 266, in _collect_params\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_q7lhwhuw/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/base.py\", line 422, in _preprocess_env\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_q7lhwhuw/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/utils/utils.py\", line 469, in parse_env_file\r\nFileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/Viettel-Digital-Talent-2023/1. Containerization/Tran-Duc-Manh/api/.env'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
fatal: [node2]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.134.132 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683742897.7667081-159871-184914554155102/AnsiballZ_docker_container.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683742897.7667081-159871-184914554155102/AnsiballZ_docker_container.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683742897.7667081-159871-184914554155102/AnsiballZ_docker_container.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.docker.plugins.modules.docker_container', init_globals=dict(_module_fqn='ansible_collections.community.docker.plugins.modules.docker_container', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_47s6hld7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1288, in <module>\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_47s6hld7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1284, in main\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_47s6hld7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 843, in run_module\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_47s6hld7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/docker_api.py\", line 369, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_47s6hld7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 840, in execute\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_47s6hld7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 211, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_47s6hld7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 272, in present\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_47s6hld7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 266, in _collect_params\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_47s6hld7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/base.py\", line 422, in _preprocess_env\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_47s6hld7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/utils/utils.py\", line 469, in parse_env_file\r\nFileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/Viettel-Digital-Talent-2023/1. Containerization/Tran-Duc-Manh/api/.env'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************
local                      : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node1                      : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node2                      : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [local]
ok: [node1]
ok: [node2]

TASK [../roles/api : include_tasks] ********************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/api/tasks/config.yml for node1, local, node2

TASK [../roles/api : Create vth group info.] ***********************************
ok: [local]
ok: [node1]
ok: [node2]

TASK [../roles/api : Create user.] *********************************************
ok: [local]
ok: [node2]
ok: [node1]

TASK [../roles/api : Check docker install.] ************************************
ok: [node2]
ok: [node1]
ok: [local]

TASK [../roles/api : include_tasks] ********************************************

TASK [../roles/api : include_tasks] ********************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/api/tasks/service.yml for node1, local, node2

TASK [../roles/api : Run the docker API images] ********************************
ok: [local]
fatal: [node2]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.134.132 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683742987.4823794-160427-125851959498585/AnsiballZ_docker_container.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683742987.4823794-160427-125851959498585/AnsiballZ_docker_container.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683742987.4823794-160427-125851959498585/AnsiballZ_docker_container.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.docker.plugins.modules.docker_container', init_globals=dict(_module_fqn='ansible_collections.community.docker.plugins.modules.docker_container', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_7m9rt3xg/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1288, in <module>\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_7m9rt3xg/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1284, in main\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_7m9rt3xg/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 843, in run_module\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_7m9rt3xg/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/docker_api.py\", line 369, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_7m9rt3xg/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 840, in execute\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_7m9rt3xg/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 211, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_7m9rt3xg/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 272, in present\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_7m9rt3xg/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 266, in _collect_params\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_7m9rt3xg/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/base.py\", line 422, in _preprocess_env\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_7m9rt3xg/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/utils/utils.py\", line 469, in parse_env_file\r\nFileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/Viettel-Digital-Talent-2023/1. Containerization/Tran-Duc-Manh/api/.env'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
fatal: [node1]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.134.131 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683742987.4646444-160422-152459538386389/AnsiballZ_docker_container.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683742987.4646444-160422-152459538386389/AnsiballZ_docker_container.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683742987.4646444-160422-152459538386389/AnsiballZ_docker_container.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.docker.plugins.modules.docker_container', init_globals=dict(_module_fqn='ansible_collections.community.docker.plugins.modules.docker_container', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vb6gtsj7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1288, in <module>\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vb6gtsj7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1284, in main\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vb6gtsj7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 843, in run_module\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vb6gtsj7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/docker_api.py\", line 369, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vb6gtsj7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 840, in execute\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vb6gtsj7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 211, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vb6gtsj7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 272, in present\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vb6gtsj7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 266, in _collect_params\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vb6gtsj7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/base.py\", line 422, in _preprocess_env\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vb6gtsj7/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/utils/utils.py\", line 469, in parse_env_file\r\nFileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/Viettel-Digital-Talent-2023/1. Containerization/Tran-Duc-Manh/api/.env'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************
local                      : ok=7    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
node1                      : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node2                      : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [local]
ok: [node1]
ok: [node2]

TASK [../roles/api : include_tasks] ********************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/api/tasks/config.yml for local, node1, node2

TASK [../roles/api : Create vth group info.] ***********************************
ok: [node2]
ok: [local]
ok: [node1]

TASK [../roles/api : Create user.] *********************************************
ok: [local]
ok: [node2]
ok: [node1]

TASK [../roles/api : Check docker install.] ************************************
ok: [local]
ok: [node1]
ok: [node2]

TASK [../roles/api : include_tasks] ********************************************

TASK [../roles/api : include_tasks] ********************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/api/tasks/service.yml for node1, local, node2

TASK [../roles/api : Run the docker API images] ********************************
ok: [local]
fatal: [node1]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.134.131 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683743201.8258753-160896-219481374540251/AnsiballZ_docker_container.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683743201.8258753-160896-219481374540251/AnsiballZ_docker_container.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683743201.8258753-160896-219481374540251/AnsiballZ_docker_container.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.docker.plugins.modules.docker_container', init_globals=dict(_module_fqn='ansible_collections.community.docker.plugins.modules.docker_container', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_9ppj6q4q/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1288, in <module>\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_9ppj6q4q/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1284, in main\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_9ppj6q4q/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 843, in run_module\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_9ppj6q4q/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/docker_api.py\", line 369, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_9ppj6q4q/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 840, in execute\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_9ppj6q4q/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 211, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_9ppj6q4q/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 272, in present\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_9ppj6q4q/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 266, in _collect_params\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_9ppj6q4q/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/base.py\", line 422, in _preprocess_env\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_9ppj6q4q/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/utils/utils.py\", line 469, in parse_env_file\r\nFileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/Viettel-Digital-Talent-2023/1. Containerization/Tran-Duc-Manh/api/.env'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
fatal: [node2]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.134.132 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683743201.8465278-160898-130706856206808/AnsiballZ_docker_container.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683743201.8465278-160898-130706856206808/AnsiballZ_docker_container.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683743201.8465278-160898-130706856206808/AnsiballZ_docker_container.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.docker.plugins.modules.docker_container', init_globals=dict(_module_fqn='ansible_collections.community.docker.plugins.modules.docker_container', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_o7wyx15c/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1288, in <module>\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_o7wyx15c/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1284, in main\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_o7wyx15c/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 843, in run_module\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_o7wyx15c/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/docker_api.py\", line 369, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_o7wyx15c/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 840, in execute\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_o7wyx15c/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 211, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_o7wyx15c/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 272, in present\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_o7wyx15c/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 266, in _collect_params\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_o7wyx15c/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/base.py\", line 422, in _preprocess_env\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_o7wyx15c/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/utils/utils.py\", line 469, in parse_env_file\r\nFileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/Viettel-Digital-Talent-2023/1. Containerization/Tran-Duc-Manh/api/.env'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************
local                      : ok=7    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
node1                      : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node2                      : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [node2]
ok: [node1]
ok: [local]

TASK [../roles/api : include_tasks] ********************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/api/tasks/config.yml for local, node1, node2

TASK [../roles/api : Create vth group info.] ***********************************
ok: [local]
ok: [node2]
ok: [node1]

TASK [../roles/api : Create user.] *********************************************
ok: [local]
ok: [node1]
ok: [node2]

TASK [../roles/api : Check docker install.] ************************************
ok: [node1]
ok: [local]
ok: [node2]

TASK [../roles/api : include_tasks] ********************************************

TASK [../roles/api : include_tasks] ********************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/api/tasks/service.yml for local, node1, node2

TASK [../roles/api : Run the docker API images] ********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: 'files/.env'
fatal: [local]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1683743257.700536-161389-154972070495948/AnsiballZ_docker_container.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1683743257.700536-161389-154972070495948/AnsiballZ_docker_container.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1683743257.700536-161389-154972070495948/AnsiballZ_docker_container.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.docker.plugins.modules.docker_container', init_globals=dict(_module_fqn='ansible_collections.community.docker.plugins.modules.docker_container', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.docker.docker_container_payload_i9ekovp6/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1288, in <module>\n  File \"/tmp/ansible_community.docker.docker_container_payload_i9ekovp6/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1284, in main\n  File \"/tmp/ansible_community.docker.docker_container_payload_i9ekovp6/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 843, in run_module\n  File \"/tmp/ansible_community.docker.docker_container_payload_i9ekovp6/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/docker_api.py\", line 369, in run\n  File \"/tmp/ansible_community.docker.docker_container_payload_i9ekovp6/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 840, in execute\n  File \"/tmp/ansible_community.docker.docker_container_payload_i9ekovp6/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 211, in run\n  File \"/tmp/ansible_community.docker.docker_container_payload_i9ekovp6/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 272, in present\n  File \"/tmp/ansible_community.docker.docker_container_payload_i9ekovp6/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 266, in _collect_params\n  File \"/tmp/ansible_community.docker.docker_container_payload_i9ekovp6/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/base.py\", line 422, in _preprocess_env\n  File \"/tmp/ansible_community.docker.docker_container_payload_i9ekovp6/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/utils/utils.py\", line 469, in parse_env_file\nFileNotFoundError: [Errno 2] No such file or directory: 'files/.env'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
fatal: [node1]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.134.131 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683743257.7306764-161390-252169211554112/AnsiballZ_docker_container.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683743257.7306764-161390-252169211554112/AnsiballZ_docker_container.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683743257.7306764-161390-252169211554112/AnsiballZ_docker_container.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.docker.plugins.modules.docker_container', init_globals=dict(_module_fqn='ansible_collections.community.docker.plugins.modules.docker_container', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_v6lbs8bl/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1288, in <module>\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_v6lbs8bl/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1284, in main\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_v6lbs8bl/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 843, in run_module\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_v6lbs8bl/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/docker_api.py\", line 369, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_v6lbs8bl/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 840, in execute\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_v6lbs8bl/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 211, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_v6lbs8bl/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 272, in present\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_v6lbs8bl/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 266, in _collect_params\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_v6lbs8bl/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/base.py\", line 422, in _preprocess_env\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_v6lbs8bl/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/utils/utils.py\", line 469, in parse_env_file\r\nFileNotFoundError: [Errno 2] No such file or directory: 'files/.env'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
fatal: [node2]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.134.132 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683743257.7213438-161400-247467556705045/AnsiballZ_docker_container.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683743257.7213438-161400-247467556705045/AnsiballZ_docker_container.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683743257.7213438-161400-247467556705045/AnsiballZ_docker_container.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.docker.plugins.modules.docker_container', init_globals=dict(_module_fqn='ansible_collections.community.docker.plugins.modules.docker_container', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_lt555fuz/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1288, in <module>\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_lt555fuz/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1284, in main\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_lt555fuz/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 843, in run_module\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_lt555fuz/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/docker_api.py\", line 369, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_lt555fuz/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 840, in execute\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_lt555fuz/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 211, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_lt555fuz/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 272, in present\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_lt555fuz/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 266, in _collect_params\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_lt555fuz/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/base.py\", line 422, in _preprocess_env\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_lt555fuz/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/utils/utils.py\", line 469, in parse_env_file\r\nFileNotFoundError: [Errno 2] No such file or directory: 'files/.env'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************
local                      : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node1                      : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node2                      : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [node1]
ok: [node2]
ok: [local]

TASK [../roles/api : include_tasks] ********************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/api/tasks/config.yml for node1, local, node2

TASK [../roles/api : Create vth group info.] ***********************************
ok: [local]
ok: [node2]
ok: [node1]

TASK [../roles/api : Create user.] *********************************************
ok: [local]
ok: [node1]
ok: [node2]

TASK [../roles/api : Check docker install.] ************************************
ok: [node2]
ok: [local]
ok: [node1]

TASK [../roles/api : include_tasks] ********************************************

TASK [../roles/api : include_tasks] ********************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/api/tasks/service.yml for node1, local, node2

TASK [../roles/api : Run the docker API images] ********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: '../files/.env'
fatal: [local]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1683743298.1276553-161848-12005829218186/AnsiballZ_docker_container.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1683743298.1276553-161848-12005829218186/AnsiballZ_docker_container.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1683743298.1276553-161848-12005829218186/AnsiballZ_docker_container.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.docker.plugins.modules.docker_container', init_globals=dict(_module_fqn='ansible_collections.community.docker.plugins.modules.docker_container', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.docker.docker_container_payload_aq3wg43b/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1288, in <module>\n  File \"/tmp/ansible_community.docker.docker_container_payload_aq3wg43b/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1284, in main\n  File \"/tmp/ansible_community.docker.docker_container_payload_aq3wg43b/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 843, in run_module\n  File \"/tmp/ansible_community.docker.docker_container_payload_aq3wg43b/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/docker_api.py\", line 369, in run\n  File \"/tmp/ansible_community.docker.docker_container_payload_aq3wg43b/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 840, in execute\n  File \"/tmp/ansible_community.docker.docker_container_payload_aq3wg43b/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 211, in run\n  File \"/tmp/ansible_community.docker.docker_container_payload_aq3wg43b/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 272, in present\n  File \"/tmp/ansible_community.docker.docker_container_payload_aq3wg43b/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 266, in _collect_params\n  File \"/tmp/ansible_community.docker.docker_container_payload_aq3wg43b/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/base.py\", line 422, in _preprocess_env\n  File \"/tmp/ansible_community.docker.docker_container_payload_aq3wg43b/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/utils/utils.py\", line 469, in parse_env_file\nFileNotFoundError: [Errno 2] No such file or directory: '../files/.env'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
fatal: [node2]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.134.132 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683743298.1612058-161858-45948416020696/AnsiballZ_docker_container.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683743298.1612058-161858-45948416020696/AnsiballZ_docker_container.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683743298.1612058-161858-45948416020696/AnsiballZ_docker_container.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.docker.plugins.modules.docker_container', init_globals=dict(_module_fqn='ansible_collections.community.docker.plugins.modules.docker_container', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_8svo6l9m/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1288, in <module>\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_8svo6l9m/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1284, in main\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_8svo6l9m/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 843, in run_module\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_8svo6l9m/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/docker_api.py\", line 369, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_8svo6l9m/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 840, in execute\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_8svo6l9m/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 211, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_8svo6l9m/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 272, in present\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_8svo6l9m/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 266, in _collect_params\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_8svo6l9m/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/base.py\", line 422, in _preprocess_env\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_8svo6l9m/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/utils/utils.py\", line 469, in parse_env_file\r\nFileNotFoundError: [Errno 2] No such file or directory: '../files/.env'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
fatal: [node1]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.134.131 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683743298.1505973-161849-265825560997581/AnsiballZ_docker_container.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683743298.1505973-161849-265825560997581/AnsiballZ_docker_container.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1683743298.1505973-161849-265825560997581/AnsiballZ_docker_container.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.docker.plugins.modules.docker_container', init_globals=dict(_module_fqn='ansible_collections.community.docker.plugins.modules.docker_container', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vv9nh_j0/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1288, in <module>\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vv9nh_j0/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1284, in main\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vv9nh_j0/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 843, in run_module\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vv9nh_j0/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/docker_api.py\", line 369, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vv9nh_j0/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 840, in execute\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vv9nh_j0/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 211, in run\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vv9nh_j0/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 272, in present\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vv9nh_j0/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/module.py\", line 266, in _collect_params\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vv9nh_j0/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/module_container/base.py\", line 422, in _preprocess_env\r\n  File \"/tmp/ansible_community.docker.docker_container_payload_vv9nh_j0/ansible_community.docker.docker_container_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/utils/utils.py\", line 469, in parse_env_file\r\nFileNotFoundError: [Errno 2] No such file or directory: '../files/.env'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************
local                      : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node1                      : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node2                      : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

